#!/usr/bin/env bash
# install nginx on the server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# sudo sed -i 's/#listen 80;/listen 80;/' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
