#!/usr/bin/env bash
# install nginx on the server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# sudo sed -i 's/#listen 80;/listen 80;/' /etc/nginx/sites-available/default

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "48i\\\tif (\$request_filename ~ redirect_me){\n\t\t\
rewrite ^ https://github.com/tech2world permanent;\n\t}" /etc/nginx/sites-available/default

sudo service nginx restart
