#!/usr/bin/env bash
# Install the web server 'nginx' on the server and perform some configurations
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
# custom index page
echo "Hello World!" > /var/www/html/index.html

# new sever config
new_website=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
                root /var/www/html;
        index index.html index.htm index.nginx-debian.html 404.html;
        server_name _;
        
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page   404  =  /404.html;
        location =  /404.html {
                internal;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/ permanent;
        }
}"

# redirection
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$new_website" > /etc/nginx/sites-available/default

# start nginx
if [ "$(pgrep nginx)" -le 0 ];
then
    sudo service nginx start
else
    sudo service nginx restart
fi;
