#!/usr/bin/env bash
# install nginx
apt-get update
apt-get install nginx -y

# create a custom header
sed -i "47\\\tadd_header X-served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > var/www/html/404.html 

# Restart Nginx
service nginx restart
