#!/usr/bin/env bash
#creates a file named /var/run/myscript.pid containing its PID
#displays 'To infinity and beyond' indefinitely
#diplays 'I hate the kill command' when receiving the SIGTERM signal
#displays 'Y U no lve me?!' when receiving the SIGINT signal
#deletes the file /var/run/myscript.pid and terminates when receiveing the
#SIGQUIT OR SIGTERM signal

echo $$ > /var/run/myscript.pid
while true
do
	trap "echo 'I hate the kill command'" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT SIGTERM
	echo "To infinity and beyond"
	sleep 2
done
