#!/usr/bin/env bash
#when passed the arg 'start':
#starts manage_my_process; creates a file containing its PID in /var/run/my_process.pid
#when passed the arg 'stop':
#stop manage_my_process; deletse /var/run/my_process.pid
#when passed the arg 'restart':
#stop manage my_process; delete /var/run/my_process.pid
#starts 'manage_my_process'; create /var/run/my_process.pid file to store its PID
#display 'Usage: manage_my_process {start|stop|restart} if any/no argument is passed.'

if [ "$1" == "start" ]
then
	./manage_my_process &
	echo $$ > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	kill "$(pgrep -f /manage_my_process)"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	kill "$(pgrep -f manage_my_process)"
	rm -f /var/run/my_process.pid
	./manage_my_process &
	echo $$ >> /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
