#!/usr/bin/env bash
# A script that prints 'Best school' 10 times but for the 9th time
# prints 'Best School' then 'Hi' on a new line using while loop and if

i=1

while [ $i -lt 11 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    ((i++))
done
