#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59

#You must use the while loop (for and until are forbidden)

hour="0"

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    mins=1
    while [ $mins -lt 60 ]
    do
        echo "$mins"
    (( mins++))
    done
(( hour++ ))
done